= A feladat megoldásához a csatolt orszagok.txt és varosok.txt fájlokat kell használni. Ezek a fájlok egy országlistát, illetve egy városlistát tárolnak. Utóbbi fájlban értelemszerűen tároljuk azt is, hogy egy-egy város melyik országban található.


== Az orszagok.txt fájl felépítése:
- Hárombetűs országkód
- Ország neve
- Kontinens
- Régió
- Terület
- Függetlenség elnyerésének időpontja (évszám vagy NULL)
- Populáció
- Államfő neve

== A varosok.txt fájl felépítése:
- Város neve
- Hárombetűs országkód (ahol a város található)
- Város populációja


A feladatmegoldás közben ügyelj a kódformázásra és elnevezésekre is! (Ha a megoldásodban sok a rosszul formázott kód, magyar elnevezések vannak, a feladatban leírtaktól eltérsz, etc. azt mínusz pontokkal jutalmazzuk.)

Figyelj a helyes hibakezelésre, a kezelendő hibák ne érjék el a main metódust!

A bemeneti fájlokat ne változtasd meg, a végeredménynek az eredeti fájlokra kell helyesen működnie!

Kiemelten figyelj a feladatokban meghatározott package-k, osztályok és metódusok szignatúrájára, hibás vagy hiányzó metódusok automatikusan 0 pontot érnek!

Fordítási hibát tartalmazó kód automatikusan 0 pontot ér, figyelj oda mit adsz be!

'''

=== Feladatok

'''

1. Hozd létre az adatokat tároló osztályokat! (Gondolj arra is, hogy az országok és a városok között kétirányú kapcsolat van!)
A létrehozott osztályok nevei legyenek Country és City és helyezkedjenek el egy modell package-ben!
Hozz létre egy module package-t és benne egy WorldStatistics osztályt is, ebbe írd majd a 4-9 feladatok megoldásait!
3 pont


2. A Country osztályba írj egy
public double getPopulationDensity()
metódust, ami visszaadja az adott ország népsűrűségét fő/km2-ben! Ha az ország területe vagy népessége nincs megadva, akkor metódusod -1-gyel térjen vissza!
2 pont


3. A Country osztályba írj egy
public double getRuralPopulation()
metódust, ami visszaadja, hogy az adott országban hány fő él a felsorolt városokon kívül!
2 pont


4. rj egy olyan metódust, ami országkód alapján visszaadja egy ország összes adatát! A metódus szignatúrája az alábbi legyen:
public Country findCountryByISoCode(List<Country> countries, String isoCode)
1 pont


5. Írj egy olyan metódust, amely visszaadja egy paraméterül kapott kontinens országainak az országkódjait! A metódus szignatúrája az alábbi legyen:
public ArrayList<String> getCountriesOfContinent(List<Country> countries,String continentName)
1 pont


6. Írj egy olyan metódust, amely visszaadja egy paraméterül kapott ország városainak a neveit (az országot országkóddal adjuk meg)! A metódus szignatúrája az alábbi legyen:
public HashSet<String> getCitiesOfCountry(List<Country> countries, String countryCode)
2 pont


7. Hány országnak az államfőjének nevében szerepel “Hamad” vagy “Ahmad” vagy “Ahmed”? A metódus szignatúrája az alábbi legyen:
public int getAhmedCount(List<Country> countries)
2 pont


8. Melyik betűvel kezdődik a legtöbb országkód? A visszatérési érték egy egybetűs String, a metódus szignatúrája pedig az alábbi legyen:
public String getPopularFirstLetter(List<Country> countries)
3 pont


9. Melyik ország nyerte el legkésőbb (a nyilvántartás szerint) a függetlenségét? Add vissza a megfelelő országkódot, a metódus szignatúrája az alábbi legyen:
public String lastIndependentCountry(List<Country> countries)
2 pont


10. Bónusz A City osztályba írj egy
public double getPopulationPercentage()
metódust, ami visszaadja, hogy az adott város populációja hány százaléka az anyaország populációjának! Ha akár a város, akár az anyaország populációja nincs megadva, a metódusod -1-gyel térjen vissza!
3 pont
